version: "3"
services:
  angular-app:
    container_name: angular-container
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    working_dir: /app
    command: ["ng", "serve", "--host", "0.0.0.0"]
